name: Gerar e publicar Docker image

# Qual evento dispara o fluxo de trabalho ?
on:
    push:
        branches:
            - base-ubuntu-prod

jobs:
    # Nome do job
    build-and-push:
        # Nome do Runner / Imagem
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do código fonte
              uses: actions/checkout@v2

            - name: Logue no DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: Contrução e publicação da imagem Docker
              uses: docker/build-push-action@v2
              with:
                context: ./base-ubuntu
                push: true
                tags: ${{secrets.DOCKERHUB_USERNAME}}/base-ubuntu:stable